repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-ast
      - id: check-builtin-literals
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-added-large-files # check for file bigger than 500kb
      - id: debug-statements
      - id: trailing-whitespace
        exclude: '.*\.bin'
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: '.*\.bin'
      - id: end-of-file-fixer
        exclude: '.*\.bin'
      - id: fix-byte-order-marker
        exclude: '.*\.bin'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
