[project]
name = 'pt-repost'
version = '0'
requires-python = '~=3.10'

[tool.pytest.ini_options]
cache_dir = '.venv/.cache/pytest'
pythonpath = [
    "src"
]

[tool.mypy]
mypy_path = '$MYPY_CONFIG_FILE_DIR'
python_version = '3.10'
#strict = true
allow_redefinition = true
ignore_missing_imports = true
check_untyped_defs = true
warn_no_return = false
warn_redundant_casts = true
explicit_package_bases = true

[tool.ruff.lint]
extend-select = ['I']
