[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
uuid-utils = "^0.9.0"
qbittorrent-api = "^2024.10.68"
click = "^8.1.7"
sslog = "^0.0.0a51"
pydantic = "^2.9.2"
httpx = "^0.27.2"
jmespath = "^1.0.1"
rich = '*'
guessit = '3.8.0'
bencode2 = '>=0.3.15'
tomli = "^2.1.0"

[tool.pytest.ini_options]
cache_dir = '.venv/.cache/pytest'
pythonpath = [
    "src"
]

[tool.mypy]
mypy_path = '$MYPY_CONFIG_FILE_DIR'
python_version = '3.10'
#strict = true
allow_redefinition = true
ignore_missing_imports = true
check_untyped_defs = true
warn_no_return = false
warn_redundant_casts = true
explicit_package_bases = true

[tool.ruff.lint]
extend-select = ['I']