version: 3

tasks:
  build:
    cmds:
      - PYTHONPATH=. pyinstaller.exe --onefile --specpath etc/pyinstaller/ --collect-all=babelfish --collect-all=app main.py main.py
      - ./dist/main.exe

  sync: poetry install --sync
  lock:
    - poetry lock
    - poetry install --sync
