name: build

on:
  push:
    paths-ignore:
      - "*.md"
    branches:
      - daemon
  pull_request:
    paths-ignore:
      - "*.md"
    branches:
      - daemon

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04-arm, ubuntu-24.04]
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        if: ${{ github.event_name == 'push' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}"
          tags: |
            type=ref,event=branch,suffix=-${{ github.sha }}-${{ runner.arch }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=buildkit-${{ runner.arch }}
          cache-to: type=gha,mode=max,scope=buildkit-${{ runner.arch }}
          github-token: ${{ github.token }}

  merge:
    if: ${{ github.event_name == 'push' }}
    needs:
      - docker
    runs-on: "ubuntu-24.04"
    permissions:
      packages: write
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Create SHA manifest and push
        run: |
          docker manifest create \
            ${{ env.IMAGE }}:daemon-${{ github.sha }} \
            --amend ${{ env.IMAGE }}:daemon-${{ github.sha }}-X64 \
            --amend ${{ env.IMAGE }}:daemon-${{ github.sha }}-ARM64 \

      - name: push sha image
        run: docker manifest push ${{ env.IMAGE }}:daemon-${{ github.sha }}

      - name: Create branch manifest and push
        run: |
          docker manifest create \
            ${{ env.IMAGE }}:daemon \
            --amend ${{ env.IMAGE }}:daemon-${{ github.sha }}-X64 \
            --amend ${{ env.IMAGE }}:daemon-${{ github.sha }}-ARM64 \

      - name: push branch image
        run: docker manifest push ${{ env.IMAGE }}:daemon
