name: build

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - daemon
  pull_request:
    paths-ignore:
      - '*.md'
    branches:
      - daemon

jobs:
  docker:
    runs-on: "ubuntu-latest"
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        if: ${{ github.event_name == 'push' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: 'ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}'
          tags: |
            type=ref,event=branch
            type=ref,event=branch,suffix=-{{ sha }}

            type=raw,value=${{ env.SHA }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          provenance: false
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          github-token: ${{ github.token }}
