name: build

on:
  push:
    paths-ignore:
      - "*.md"
    branches:
      - daemon
  pull_request:
    paths-ignore:
      - "*.md"
    branches:
      - daemon

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04-arm, ubuntu-24.04]
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        if: ${{ github.event_name == 'push' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}"
          tags: |
            type=ref,event=branch,suffix=-${{ github.sha }}-${{ runner.arch }}

      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v4
        with:
          path: ./cache/docker
          key: docker-daemon-${{ runner.arch }}-${{ github.sha }}
          restore-keys: |
            docker-daemon-${{ runner.arch }}-

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=./cache/docker
          cache-to: type=local,dest=./cache/docker
          github-token: ${{ github.token }}

      - name: prune docker cache
        run: docker buildx prune --filter=24h --all

  merge:
    if: ${{ github.event_name == 'push' }}
    needs:
      - docker
    runs-on: "ubuntu-24.04"
    permissions:
      packages: write
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Create SHA manifest and push
        run: |
          docker manifest create \
            ${{ env.IMAGE }}:daemon-${{ github.sha }} \
            --amend ${{ env.IMAGE }}:daemon-${{ github.sha }}-X64 \
            --amend ${{ env.IMAGE }}:daemon-${{ github.sha }}-ARM64 \

      - run: docker manifest create ${{ env.IMAGE }}:daemon ${{ env.IMAGE }}:daemon-${{ github.sha }}
