name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - run: pip install pyoxidizer

      - run: pip install -r requirements.txt

      - run: pyoxidizer build --release

      - name: check binary
        shell: bash
        run: |
          cd build/*/release/install/
          ./pt-repost/pt-repost --help
        if: runner.os != 'Windows'

      - name: check windows binary
        shell: bash
        run: |
          cd build/*/release/install/
          ./pt-repost/pt-repost.exe --help
        if: runner.os == 'Windows'

      - uses: actions/upload-artifact@v4
        with:
          name: 'wheels-${{ runner.os }}'
          path: ./build/*
