name: lint

on:
  push:
    branches:
      - master
      - daemon
  pull_request:
    branches:
      - master
      - daemon

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - run: uv sync --frozen

      - uses: liskin/gh-problem-matcher-wrap@v3
        with:
          action: add
          linters: mypy
          run: ""

      - run: uv run mypy --show-column-numbers .

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
          cache: pip

      - run: pip install pre-commit

      - uses: trim21/actions/pre-commit@master
