name: lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - run: pip install -r requirements.txt

      - uses: liskin/gh-problem-matcher-wrap@v3
        with:
          action: add
          linters: mypy
          run: mypy --show-column-numbers src/

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - run: pip install -r requirements.txt

      - uses: trim21/actions/pre-commit@master
